package game.board.tile;

import game.board.tile.build.Build;
import game.player.Player;
import game.player.inventory.Inventory;
import game.resource.Resource;

/**
 * BuildableTile class - Represents a tile that can have a build placed on it.
 */
public abstract class BuildableTile extends Tile {
    /**
     * The build placed on the tile, if any.
     */
    protected Build build;
    /**
     * The player who owns the tile, if any.
     */
    protected Player owner;
    /**
     * The resource generated by the tile, if any.
     */
    protected Resource generatedResource;

    /**
     * Constructs a Buildable Tile.
     */
    public BuildableTile() {
        super();
        this.owner = null;
        this.generatedResource = null;
        this.build = null;
    }

    /**
     * Sets the owner of the tile.
     * 
     * @param owner the player who owns this tile
     * @throws TileNotOwnableException if the player can own this tile
     */
    public void setOwner(Player owner) throws TileNotOwnableException {
        if (this.owner != null) {
            throw new TileNotOwnableException("The tile already has an owner.");
        }
        this.owner = owner;
    }

    /**
     * Change the owner of the tile.
     * 
     * @param owner the player who owns this tile
     */
    public void changeOwner(Player owner) {
        this.owner = owner;
    }

    /**
     * Gets the owner of the tile.
     * 
     * @return the player who owns this tile, or null if no owner is assigned
     */
    public Player getOwner() {
        return this.owner;
    }

    /**
     * Sets a build on the tile.
     * 
     * @param build  the build to place on the tile
     * @param player the player who owns the build
     * @throws TileNotBuildableException if the tile cannot accommodate a build
     * @throws TileNotOwnableException   if the player cannot own the tile
     */
    public void setBuild(Build build, Player player) throws TileNotBuildableException, TileNotOwnableException {
        
        if (this.build != null) {
            throw new TileNotBuildableException("The tile already has a build. " + this.build.toString() );
        }
        this.setOwner(player);
        this.build = build;
    }

    /**
     * Upgrades the build on the tile.
     * 
     * @param build the build to upgrade to
     */
    public void upgradeBuild(Build build) {
        this.build = build;
    }

    /**
     * Checks whether the tile has a build on it.
     * 
     * @return true if the tile has a build, false otherwise
     */
    public boolean hasBuild() {
        return this.build != null;
    }

    /**
     * Removes the build from the tile, if one exists.
     */
    public void resetBuild() {
            this.build = null;
    }

    /*
     * Resets the state of the tile by removing its build and clearing its owner.
     */
    public void resetTile() {
        this.resetBuild();
        this.owner = null;

    }

    /**
     * Gets the build currently placed on the tile.
     *
     * @return the build on this tile, or null if no build is present
     */
    public Build getBuild() {
        return this.build;
    }

    /**
     * Gets the type of resource generated by the tile.
     * 
     * @return the resource type generated by the tile, or null if none is assigned
     */
    public Resource getResource() {
        return this.generatedResource;
    }

    /**
     * Harvests the resource generated by the tile.
     * 
     * @return inventory with the generated resource of the tile
     */
    public Inventory harvest() {
        Inventory inventory = new Inventory();
        if (this.generatedResource != null) {
            inventory.addResource(this.generatedResource, this.build.isUpgraded() ? 2 : 1);
        }
        return inventory;
    }

    /**
     * String the owner of the tile if the tile had a owner and the build if the
     * tile had build
     * 
     * @return the string of the tile
     */
    @Override
    public String toString() {
        if (this.owner != null && this.build != null) {
            return owner.toString() + build.toString();
        }
        if (this.owner != null) {
            return owner.toString() + " ";
        }
        if (this.build != null) {
            return " " + build.toString();
        } else {
            return "  ";
        }
    }
}
